version: "3.3"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_USER: "user"
      MYSQL_PASSWORD: "pass"
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_ROOT_HOST: '127.0.0.1'
    networks:
      - app-network
  backend:
    build: . # Build image from local Dockerfile
    # command: ["./wait-for-it/wait-for-it.sh", "db:3306", "--", "yarn",  "start:prod"]
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; yarn start:prod'
    ports:
      - "8080:8080"
    depends_on:
      - db # Wait until database service is loaded
    networks:
      - app-network
networks: # Specify the network for bridging
  app-network:
    driver: bridge